name: aas229-workshop

channels:
  - http://ssb.stsci.edu/astroconda

dependencies:
  - python=3.5
  - numpy>=1.7
  - scipy>=0.15
  - cython
  - matplotlib>=1.3
  - astropy>=1.2.1
  - photutils>=0.3
  - imexam>=0.6.2
  - scikit-image>=0.12.3
  - pandas>=0.18.1
  - glue-vispy-viewers>=0.6
  - glueviz>=0.9.1
  - ginga>=2.6.1
  - stginga
  - specutils
  - specviz
  - jupyter
  - notebook
  - ipython
  - asdf
  - gwcs>=0.7
  - beautifulsoup4
  - requests
  - keyring
  - html5lib
  - ds9>=7.1
  - pip:
    - astroquery
