name: astropy-workshop

channels:
  - astropy

dependencies:
  - pip
  - python=3.7
  - ipython>=7.2
  - cython
  - jupyter
  - notebook>=5.7
  - numpy>=1.16
  - scipy>=1.1
  - scikit-image>=0.14
  - matplotlib>=2.2.3
  - pandas>=0.23
  - pip:
    - pytest
    - beautifulsoup4
    - keyring
    - html5lib
    - xlwt
    - requests
    - jupyterlab
    - "astropy>=4.0"
    - asdf
    - "gwcs>=0.10"
    - "photutils>=0.7.2"
    - "specutils>=0.5.1"
    - "glue-vispy-viewers>=0.6"
    - "glueviz>=0.9.1"
    - astroquery
    - --pre
