name: astropy-workshop

channels:
  - http://ssb.stsci.edu/astroconda

dependencies:
  - python=3.5
  - numpy>=1.7
  - scipy>=0.15
  - cython
  - matplotlib>=1.3
  - astropy>=1.2.1
  - photutils>=0.4
  - scikit-image>=0.12.3
  - pandas>=0.18.1
  - specutils
  - jupyter
  - notebook
  - ipython
  - asdf
  - gwcs>=0.7
  - beautifulsoup4
  - requests
  - keyring
  - html5lib
  - ds9>=7.1
  - pip:
    - astroquery
    - wcsaxes
